name: OTP Pipline
run-name: "OTP Pipline - v${{env.OTP_VERSION}})"
on:
  workflow_dispatch:
env:
  OTP_VERSION: ${{needs.release-otp.outputs.version}}
jobs:
  release-otp:
    name: "Build, test, tag & release OTP"
    uses: ./.github/workflows/otp-release.yml

  build-docker-image:
    name: Build and publish docker image
    uses: ./.github/workflows/otp-build-docker-image.yml
    needs: release-otp
    with:
      version: ${{needs.release-otp.outputs.version}}
      ser_ver_id: ${{needs.release-otp.outputs.ser_ver_id}}

  deploy-otp-dev:
    name: Deploy OTP to DEV
    uses: ./.github/workflows/otp-deploy-pipeline.yml
    needs: [release-otp, build-docker-image]
    with:
      version: ${{needs.release-otp.outputs.version}}
      ser_ver_id: ${{needs.release-otp.outputs.ser_ver_id}}
      target: dev

  deploy-otp-test:
    name: Deploy OTP to TEST
    uses: ./.github/workflows/otp-deploy-pipeline.yml
    needs: [release-otp, build-docker-image]
    with:
      version: ${{needs.release-otp.outputs.version}}
      ser_ver_id: ${{needs.release-otp.outputs.ser_ver_id}}
      target: test
